package net.carverse.model;
// Generated 21 lis 2022, 14:48:23 by Hibernate Tools 6.1.3.Final

import java.sql.Timestamp;

/**
 * Komentarze generated by hbm2java
 */
public class Komentarze implements java.io.Serializable {

	private Integer id;
	private Samochody samochody;
	private Uzytkownicy uzytkownicy;
	private String komentarz;
	private Timestamp dataUtworzenia;
	private int ocena;

	public Komentarze() {
	}

	public Komentarze(Samochody samochody, Uzytkownicy uzytkownicy, String komentarz, Timestamp dataUtworzenia,
			int ocena) {
		this.samochody = samochody;
		this.uzytkownicy = uzytkownicy;
		this.komentarz = komentarz;
		this.dataUtworzenia = dataUtworzenia;
		this.ocena = ocena;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Samochody getSamochody() {
		return this.samochody;
	}

	public void setSamochody(Samochody samochody) {
		this.samochody = samochody;
	}

	public Uzytkownicy getUzytkownicy() {
		return this.uzytkownicy;
	}

	public void setUzytkownicy(Uzytkownicy uzytkownicy) {
		this.uzytkownicy = uzytkownicy;
	}

	public String getKomentarz() {
		return this.komentarz;
	}

	public void setKomentarz(String komentarz) {
		this.komentarz = komentarz;
	}

	public Timestamp getDataUtworzenia() {
		return this.dataUtworzenia;
	}

	public void setDataUtworzenia(Timestamp dataUtworzenia) {
		this.dataUtworzenia = dataUtworzenia;
	}

	public int getOcena() {
		return this.ocena;
	}

	public void setOcena(int ocena) {
		this.ocena = ocena;
	}

}
