package net.carverse.model;
// Generated 21 lis 2022, 14:48:23 by Hibernate Tools 6.1.3.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Lokacje generated by hbm2java
 */
public class Lokacje implements java.io.Serializable {

	private Integer id;
	private String kraj;
	private String miasto;
	private String adres;
	private String email;
	private String telefon;
	private Set samochodies = new HashSet(0);
	private Set rezerwacjes = new HashSet(0);

	public Lokacje() {
	}

	public Lokacje(String kraj, String miasto, String adres, String email, String telefon) {
		this.kraj = kraj;
		this.miasto = miasto;
		this.adres = adres;
		this.email = email;
		this.telefon = telefon;
	}

	public Lokacje(String kraj, String miasto, String adres, String email, String telefon, Set samochodies,
			Set rezerwacjes) {
		this.kraj = kraj;
		this.miasto = miasto;
		this.adres = adres;
		this.email = email;
		this.telefon = telefon;
		this.samochodies = samochodies;
		this.rezerwacjes = rezerwacjes;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getKraj() {
		return this.kraj;
	}

	public void setKraj(String kraj) {
		this.kraj = kraj;
	}

	public String getMiasto() {
		return this.miasto;
	}

	public void setMiasto(String miasto) {
		this.miasto = miasto;
	}

	public String getAdres() {
		return this.adres;
	}

	public void setAdres(String adres) {
		this.adres = adres;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getTelefon() {
		return this.telefon;
	}

	public void setTelefon(String telefon) {
		this.telefon = telefon;
	}

	public Set getSamochodies() {
		return this.samochodies;
	}

	public void setSamochodies(Set samochodies) {
		this.samochodies = samochodies;
	}

	public Set getRezerwacjes() {
		return this.rezerwacjes;
	}

	public void setRezerwacjes(Set rezerwacjes) {
		this.rezerwacjes = rezerwacjes;
	}

}
