package net.carverse.model;
// Generated 21 lis 2022, 14:48:23 by Hibernate Tools 6.1.3.Final

/**
 * ParametrysamochoduId generated by hbm2java
 */
public class ParametrysamochoduId implements java.io.Serializable {

	private int idsamochodu;
	private String kolor;
	private int liczbaDrzwi;
	private int liczbaSiedzen;
	private byte metaliczny;
	private int moc;
	private byte napedNaPrzednieKola;
	private String nazwaZdjecia;
	private String opis;
	private String rodzajPaliwa;
	private int rokProdukcji;
	private String skrzyniaBiegow;
	private String typNadwozia;

	public ParametrysamochoduId() {
	}

	public ParametrysamochoduId(int idsamochodu, String kolor, int liczbaDrzwi, int liczbaSiedzen, byte metaliczny,
			int moc, byte napedNaPrzednieKola, String nazwaZdjecia, String opis, String rodzajPaliwa, int rokProdukcji,
			String skrzyniaBiegow, String typNadwozia) {
		this.idsamochodu = idsamochodu;
		this.kolor = kolor;
		this.liczbaDrzwi = liczbaDrzwi;
		this.liczbaSiedzen = liczbaSiedzen;
		this.metaliczny = metaliczny;
		this.moc = moc;
		this.napedNaPrzednieKola = napedNaPrzednieKola;
		this.nazwaZdjecia = nazwaZdjecia;
		this.opis = opis;
		this.rodzajPaliwa = rodzajPaliwa;
		this.rokProdukcji = rokProdukcji;
		this.skrzyniaBiegow = skrzyniaBiegow;
		this.typNadwozia = typNadwozia;
	}

	public int getIdsamochodu() {
		return this.idsamochodu;
	}

	public void setIdsamochodu(int idsamochodu) {
		this.idsamochodu = idsamochodu;
	}

	public String getKolor() {
		return this.kolor;
	}

	public void setKolor(String kolor) {
		this.kolor = kolor;
	}

	public int getLiczbaDrzwi() {
		return this.liczbaDrzwi;
	}

	public void setLiczbaDrzwi(int liczbaDrzwi) {
		this.liczbaDrzwi = liczbaDrzwi;
	}

	public int getLiczbaSiedzen() {
		return this.liczbaSiedzen;
	}

	public void setLiczbaSiedzen(int liczbaSiedzen) {
		this.liczbaSiedzen = liczbaSiedzen;
	}

	public byte getMetaliczny() {
		return this.metaliczny;
	}

	public void setMetaliczny(byte metaliczny) {
		this.metaliczny = metaliczny;
	}

	public int getMoc() {
		return this.moc;
	}

	public void setMoc(int moc) {
		this.moc = moc;
	}

	public byte getNapedNaPrzednieKola() {
		return this.napedNaPrzednieKola;
	}

	public void setNapedNaPrzednieKola(byte napedNaPrzednieKola) {
		this.napedNaPrzednieKola = napedNaPrzednieKola;
	}

	public String getNazwaZdjecia() {
		return this.nazwaZdjecia;
	}

	public void setNazwaZdjecia(String nazwaZdjecia) {
		this.nazwaZdjecia = nazwaZdjecia;
	}

	public String getOpis() {
		return this.opis;
	}

	public void setOpis(String opis) {
		this.opis = opis;
	}

	public String getRodzajPaliwa() {
		return this.rodzajPaliwa;
	}

	public void setRodzajPaliwa(String rodzajPaliwa) {
		this.rodzajPaliwa = rodzajPaliwa;
	}

	public int getRokProdukcji() {
		return this.rokProdukcji;
	}

	public void setRokProdukcji(int rokProdukcji) {
		this.rokProdukcji = rokProdukcji;
	}

	public String getSkrzyniaBiegow() {
		return this.skrzyniaBiegow;
	}

	public void setSkrzyniaBiegow(String skrzyniaBiegow) {
		this.skrzyniaBiegow = skrzyniaBiegow;
	}

	public String getTypNadwozia() {
		return this.typNadwozia;
	}

	public void setTypNadwozia(String typNadwozia) {
		this.typNadwozia = typNadwozia;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ParametrysamochoduId))
			return false;
		ParametrysamochoduId castOther = (ParametrysamochoduId) other;

		return (this.getIdsamochodu() == castOther.getIdsamochodu())
				&& ((this.getKolor() == castOther.getKolor()) || (this.getKolor() != null
						&& castOther.getKolor() != null && this.getKolor().equals(castOther.getKolor())))
				&& (this.getLiczbaDrzwi() == castOther.getLiczbaDrzwi())
				&& (this.getLiczbaSiedzen() == castOther.getLiczbaSiedzen())
				&& (this.getMetaliczny() == castOther.getMetaliczny()) && (this.getMoc() == castOther.getMoc())
				&& (this.getNapedNaPrzednieKola() == castOther.getNapedNaPrzednieKola())
				&& ((this.getNazwaZdjecia() == castOther.getNazwaZdjecia())
						|| (this.getNazwaZdjecia() != null && castOther.getNazwaZdjecia() != null
								&& this.getNazwaZdjecia().equals(castOther.getNazwaZdjecia())))
				&& ((this.getOpis() == castOther.getOpis()) || (this.getOpis() != null && castOther.getOpis() != null
						&& this.getOpis().equals(castOther.getOpis())))
				&& ((this.getRodzajPaliwa() == castOther.getRodzajPaliwa())
						|| (this.getRodzajPaliwa() != null && castOther.getRodzajPaliwa() != null
								&& this.getRodzajPaliwa().equals(castOther.getRodzajPaliwa())))
				&& (this.getRokProdukcji() == castOther.getRokProdukcji())
				&& ((this.getSkrzyniaBiegow() == castOther.getSkrzyniaBiegow())
						|| (this.getSkrzyniaBiegow() != null && castOther.getSkrzyniaBiegow() != null
								&& this.getSkrzyniaBiegow().equals(castOther.getSkrzyniaBiegow())))
				&& ((this.getTypNadwozia() == castOther.getTypNadwozia())
						|| (this.getTypNadwozia() != null && castOther.getTypNadwozia() != null
								&& this.getTypNadwozia().equals(castOther.getTypNadwozia())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdsamochodu();
		result = 37 * result + (getKolor() == null ? 0 : this.getKolor().hashCode());
		result = 37 * result + this.getLiczbaDrzwi();
		result = 37 * result + this.getLiczbaSiedzen();
		result = 37 * result + this.getMetaliczny();
		result = 37 * result + this.getMoc();
		result = 37 * result + this.getNapedNaPrzednieKola();
		result = 37 * result + (getNazwaZdjecia() == null ? 0 : this.getNazwaZdjecia().hashCode());
		result = 37 * result + (getOpis() == null ? 0 : this.getOpis().hashCode());
		result = 37 * result + (getRodzajPaliwa() == null ? 0 : this.getRodzajPaliwa().hashCode());
		result = 37 * result + this.getRokProdukcji();
		result = 37 * result + (getSkrzyniaBiegow() == null ? 0 : this.getSkrzyniaBiegow().hashCode());
		result = 37 * result + (getTypNadwozia() == null ? 0 : this.getTypNadwozia().hashCode());
		return result;
	}

}
