package net.carverse.model;
// Generated 21 lis 2022, 14:48:23 by Hibernate Tools 6.1.3.Final

/**
 * Parametrysamochodu generated by hbm2java
 */
public class Parametrysamochodu implements java.io.Serializable {

	private ParametrysamochoduId id;
	private Samochody samochody;

	public Parametrysamochodu() {
	}

	public Parametrysamochodu(ParametrysamochoduId id, Samochody samochody) {
		this.id = id;
		this.samochody = samochody;
	}

	public ParametrysamochoduId getId() {
		return this.id;
	}

	public void setId(ParametrysamochoduId id) {
		this.id = id;
	}

	public Samochody getSamochody() {
		return this.samochody;
	}

	public void setSamochody(Samochody samochody) {
		this.samochody = samochody;
	}

}
