package net.carverse.model;
// Generated 21 lis 2022, 14:48:23 by Hibernate Tools 6.1.3.Final

import java.math.BigDecimal;
import java.sql.Timestamp;
import java.util.HashSet;
import java.util.Set;

/**
 * Rezerwacje generated by hbm2java
 */
public class Rezerwacje implements java.io.Serializable {

	private Integer id;
	private Stanrezerwacji stanrezerwacji;
	private Lokacje lokacje;
	private Samochody samochody;
	private Uzytkownicy uzytkownicy;
	private Timestamp dataOdbioru;
	private Timestamp dataZwrotu;
	private BigDecimal kosztCalkowity;
	private Set zmianyrezerwacjis = new HashSet(0);

	public Rezerwacje() {
	}

	public Rezerwacje(Stanrezerwacji stanrezerwacji, Lokacje lokacje, Samochody samochody, Uzytkownicy uzytkownicy,
			Timestamp dataOdbioru, Timestamp dataZwrotu, BigDecimal kosztCalkowity) {
		this.stanrezerwacji = stanrezerwacji;
		this.lokacje = lokacje;
		this.samochody = samochody;
		this.uzytkownicy = uzytkownicy;
		this.dataOdbioru = dataOdbioru;
		this.dataZwrotu = dataZwrotu;
		this.kosztCalkowity = kosztCalkowity;
	}

	public Rezerwacje(Stanrezerwacji stanrezerwacji, Lokacje lokacje, Samochody samochody, Uzytkownicy uzytkownicy,
			Timestamp dataOdbioru, Timestamp dataZwrotu, BigDecimal kosztCalkowity, Set zmianyrezerwacjis) {
		this.stanrezerwacji = stanrezerwacji;
		this.lokacje = lokacje;
		this.samochody = samochody;
		this.uzytkownicy = uzytkownicy;
		this.dataOdbioru = dataOdbioru;
		this.dataZwrotu = dataZwrotu;
		this.kosztCalkowity = kosztCalkowity;
		this.zmianyrezerwacjis = zmianyrezerwacjis;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Stanrezerwacji getStanrezerwacji() {
		return this.stanrezerwacji;
	}

	public void setStanrezerwacji(Stanrezerwacji stanrezerwacji) {
		this.stanrezerwacji = stanrezerwacji;
	}

	public Lokacje getLokacje() {
		return this.lokacje;
	}

	public void setLokacje(Lokacje lokacje) {
		this.lokacje = lokacje;
	}

	public Samochody getSamochody() {
		return this.samochody;
	}

	public void setSamochody(Samochody samochody) {
		this.samochody = samochody;
	}

	public Uzytkownicy getUzytkownicy() {
		return this.uzytkownicy;
	}

	public void setUzytkownicy(Uzytkownicy uzytkownicy) {
		this.uzytkownicy = uzytkownicy;
	}

	public Timestamp getDataOdbioru() {
		return this.dataOdbioru;
	}

	public void setDataOdbioru(Timestamp dataOdbioru) {
		this.dataOdbioru = dataOdbioru;
	}

	public Timestamp getDataZwrotu() {
		return this.dataZwrotu;
	}

	public void setDataZwrotu(Timestamp dataZwrotu) {
		this.dataZwrotu = dataZwrotu;
	}

	public BigDecimal getKosztCalkowity() {
		return this.kosztCalkowity;
	}

	public void setKosztCalkowity(BigDecimal kosztCalkowity) {
		this.kosztCalkowity = kosztCalkowity;
	}

	public Set getZmianyrezerwacjis() {
		return this.zmianyrezerwacjis;
	}

	public void setZmianyrezerwacjis(Set zmianyrezerwacjis) {
		this.zmianyrezerwacjis = zmianyrezerwacjis;
	}

}
