package net.carverse.model;
// Generated 21 lis 2022, 14:48:23 by Hibernate Tools 6.1.3.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Role generated by hbm2java
 */
public class Role implements java.io.Serializable {

	private Integer id;
	private String nazwa;
	private Set uzytkownicies = new HashSet(0);

	public Role() {
	}

	public Role(String nazwa) {
		this.nazwa = nazwa;
	}

	public Role(String nazwa, Set uzytkownicies) {
		this.nazwa = nazwa;
		this.uzytkownicies = uzytkownicies;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getNazwa() {
		return this.nazwa;
	}

	public void setNazwa(String nazwa) {
		this.nazwa = nazwa;
	}

	public Set getUzytkownicies() {
		return this.uzytkownicies;
	}

	public void setUzytkownicies(Set uzytkownicies) {
		this.uzytkownicies = uzytkownicies;
	}

}
