package net.carverse.model;
// Generated 21 lis 2022, 14:48:23 by Hibernate Tools 6.1.3.Final

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Samochody generated by hbm2java
 */
public class Samochody implements java.io.Serializable {

	private Integer id;
	private Lokacje lokacje;
	private Statussamochodu statussamochodu;
	private String rejestracja;
	private String marka;
	private String model;
	private BigDecimal dziennyKoszt;
	private byte najlepszaOferta;
	private Set komentarzes = new HashSet(0);
	private Set parametrysamochodus = new HashSet(0);
	private Set rezerwacjes = new HashSet(0);
	private Set gwiazdkis = new HashSet(0);
	private Set wyposazenies = new HashSet(0);

	public Samochody() {
	}

	public Samochody(Lokacje lokacje, Statussamochodu statussamochodu, String rejestracja, String marka, String model,
			BigDecimal dziennyKoszt, byte najlepszaOferta) {
		this.lokacje = lokacje;
		this.statussamochodu = statussamochodu;
		this.rejestracja = rejestracja;
		this.marka = marka;
		this.model = model;
		this.dziennyKoszt = dziennyKoszt;
		this.najlepszaOferta = najlepszaOferta;
	}

	public Samochody(Lokacje lokacje, Statussamochodu statussamochodu, String rejestracja, String marka, String model,
			BigDecimal dziennyKoszt, byte najlepszaOferta, Set komentarzes, Set parametrysamochodus, Set rezerwacjes,
			Set gwiazdkis, Set wyposazenies) {
		this.lokacje = lokacje;
		this.statussamochodu = statussamochodu;
		this.rejestracja = rejestracja;
		this.marka = marka;
		this.model = model;
		this.dziennyKoszt = dziennyKoszt;
		this.najlepszaOferta = najlepszaOferta;
		this.komentarzes = komentarzes;
		this.parametrysamochodus = parametrysamochodus;
		this.rezerwacjes = rezerwacjes;
		this.gwiazdkis = gwiazdkis;
		this.wyposazenies = wyposazenies;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Lokacje getLokacje() {
		return this.lokacje;
	}

	public void setLokacje(Lokacje lokacje) {
		this.lokacje = lokacje;
	}

	public Statussamochodu getStatussamochodu() {
		return this.statussamochodu;
	}

	public void setStatussamochodu(Statussamochodu statussamochodu) {
		this.statussamochodu = statussamochodu;
	}

	public String getRejestracja() {
		return this.rejestracja;
	}

	public void setRejestracja(String rejestracja) {
		this.rejestracja = rejestracja;
	}

	public String getMarka() {
		return this.marka;
	}

	public void setMarka(String marka) {
		this.marka = marka;
	}

	public String getModel() {
		return this.model;
	}

	public void setModel(String model) {
		this.model = model;
	}

	public BigDecimal getDziennyKoszt() {
		return this.dziennyKoszt;
	}

	public void setDziennyKoszt(BigDecimal dziennyKoszt) {
		this.dziennyKoszt = dziennyKoszt;
	}

	public byte getNajlepszaOferta() {
		return this.najlepszaOferta;
	}

	public void setNajlepszaOferta(byte najlepszaOferta) {
		this.najlepszaOferta = najlepszaOferta;
	}

	public Set getKomentarzes() {
		return this.komentarzes;
	}

	public void setKomentarzes(Set komentarzes) {
		this.komentarzes = komentarzes;
	}

	public Set getParametrysamochodus() {
		return this.parametrysamochodus;
	}

	public void setParametrysamochodus(Set parametrysamochodus) {
		this.parametrysamochodus = parametrysamochodus;
	}

	public Set getRezerwacjes() {
		return this.rezerwacjes;
	}

	public void setRezerwacjes(Set rezerwacjes) {
		this.rezerwacjes = rezerwacjes;
	}

	public Set getGwiazdkis() {
		return this.gwiazdkis;
	}

	public void setGwiazdkis(Set gwiazdkis) {
		this.gwiazdkis = gwiazdkis;
	}

	public Set getWyposazenies() {
		return this.wyposazenies;
	}

	public void setWyposazenies(Set wyposazenies) {
		this.wyposazenies = wyposazenies;
	}

}
