package net.carverse.model;
// Generated 21 lis 2022, 14:48:23 by Hibernate Tools 6.1.3.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Stanrezerwacji generated by hbm2java
 */
public class Stanrezerwacji implements java.io.Serializable {

	private String kodStanuRezerwacji;
	private String opis;
	private Set rezerwacjes = new HashSet(0);

	public Stanrezerwacji() {
	}

	public Stanrezerwacji(String kodStanuRezerwacji, String opis) {
		this.kodStanuRezerwacji = kodStanuRezerwacji;
		this.opis = opis;
	}

	public Stanrezerwacji(String kodStanuRezerwacji, String opis, Set rezerwacjes) {
		this.kodStanuRezerwacji = kodStanuRezerwacji;
		this.opis = opis;
		this.rezerwacjes = rezerwacjes;
	}

	public String getKodStanuRezerwacji() {
		return this.kodStanuRezerwacji;
	}

	public void setKodStanuRezerwacji(String kodStanuRezerwacji) {
		this.kodStanuRezerwacji = kodStanuRezerwacji;
	}

	public String getOpis() {
		return this.opis;
	}

	public void setOpis(String opis) {
		this.opis = opis;
	}

	public Set getRezerwacjes() {
		return this.rezerwacjes;
	}

	public void setRezerwacjes(Set rezerwacjes) {
		this.rezerwacjes = rezerwacjes;
	}

}
