package net.carverse.model;
// Generated 21 lis 2022, 14:48:23 by Hibernate Tools 6.1.3.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Statussamochodu generated by hbm2java
 */
public class Statussamochodu implements java.io.Serializable {

	private String kodStatusu;
	private String opis;
	private Set samochodies = new HashSet(0);

	public Statussamochodu() {
	}

	public Statussamochodu(String kodStatusu, String opis) {
		this.kodStatusu = kodStatusu;
		this.opis = opis;
	}

	public Statussamochodu(String kodStatusu, String opis, Set samochodies) {
		this.kodStatusu = kodStatusu;
		this.opis = opis;
		this.samochodies = samochodies;
	}

	public String getKodStatusu() {
		return this.kodStatusu;
	}

	public void setKodStatusu(String kodStatusu) {
		this.kodStatusu = kodStatusu;
	}

	public String getOpis() {
		return this.opis;
	}

	public void setOpis(String opis) {
		this.opis = opis;
	}

	public Set getSamochodies() {
		return this.samochodies;
	}

	public void setSamochodies(Set samochodies) {
		this.samochodies = samochodies;
	}

}
