package net.carverse.model;
// Generated 21 lis 2022, 14:48:23 by Hibernate Tools 6.1.3.Final

import java.sql.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Uzytkownicy generated by hbm2java
 */
public class Uzytkownicy implements java.io.Serializable {

	private Integer id;
	private String imie;
	private String nazwisko;
	private String login;
	private String haslo;
	private String email;
	private String telefon;
	private Date urodziny;
	private String pesel;
	private Set rezerwacjes = new HashSet(0);
	private Set roles = new HashSet(0);
	private Set komentarzes = new HashSet(0);

	public Uzytkownicy() {
	}

	public Uzytkownicy(String imie, String nazwisko, String login, String haslo, String email, String telefon,
			Date urodziny, String pesel) {
		this.imie = imie;
		this.nazwisko = nazwisko;
		this.login = login;
		this.haslo = haslo;
		this.email = email;
		this.telefon = telefon;
		this.urodziny = urodziny;
		this.pesel = pesel;
	}

	public Uzytkownicy(String imie, String nazwisko, String login, String haslo, String email, String telefon,
			Date urodziny, String pesel, Set rezerwacjes, Set roles, Set komentarzes) {
		this.imie = imie;
		this.nazwisko = nazwisko;
		this.login = login;
		this.haslo = haslo;
		this.email = email;
		this.telefon = telefon;
		this.urodziny = urodziny;
		this.pesel = pesel;
		this.rezerwacjes = rezerwacjes;
		this.roles = roles;
		this.komentarzes = komentarzes;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getImie() {
		return this.imie;
	}

	public void setImie(String imie) {
		this.imie = imie;
	}

	public String getNazwisko() {
		return this.nazwisko;
	}

	public void setNazwisko(String nazwisko) {
		this.nazwisko = nazwisko;
	}

	public String getLogin() {
		return this.login;
	}

	public void setLogin(String login) {
		this.login = login;
	}

	public String getHaslo() {
		return this.haslo;
	}

	public void setHaslo(String haslo) {
		this.haslo = haslo;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getTelefon() {
		return this.telefon;
	}

	public void setTelefon(String telefon) {
		this.telefon = telefon;
	}

	public Date getUrodziny() {
		return this.urodziny;
	}

	public void setUrodziny(Date urodziny) {
		this.urodziny = urodziny;
	}

	public String getPesel() {
		return this.pesel;
	}

	public void setPesel(String pesel) {
		this.pesel = pesel;
	}

	public Set getRezerwacjes() {
		return this.rezerwacjes;
	}

	public void setRezerwacjes(Set rezerwacjes) {
		this.rezerwacjes = rezerwacjes;
	}

	public Set getRoles() {
		return this.roles;
	}

	public void setRoles(Set roles) {
		this.roles = roles;
	}

	public Set getKomentarzes() {
		return this.komentarzes;
	}

	public void setKomentarzes(Set komentarzes) {
		this.komentarzes = komentarzes;
	}

}
