package net.carverse.model;
// Generated 21 lis 2022, 14:48:23 by Hibernate Tools 6.1.3.Final

import java.sql.Timestamp;

/**
 * Zmianyrezerwacji generated by hbm2java
 */
public class Zmianyrezerwacji implements java.io.Serializable {

	private Integer id;
	private Rezerwacje rezerwacje;
	private Timestamp dataZmiany;
	private String kto;
	private String pc;

	public Zmianyrezerwacji() {
	}

	public Zmianyrezerwacji(Rezerwacje rezerwacje, Timestamp dataZmiany, String kto, String pc) {
		this.rezerwacje = rezerwacje;
		this.dataZmiany = dataZmiany;
		this.kto = kto;
		this.pc = pc;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Rezerwacje getRezerwacje() {
		return this.rezerwacje;
	}

	public void setRezerwacje(Rezerwacje rezerwacje) {
		this.rezerwacje = rezerwacje;
	}

	public Timestamp getDataZmiany() {
		return this.dataZmiany;
	}

	public void setDataZmiany(Timestamp dataZmiany) {
		this.dataZmiany = dataZmiany;
	}

	public String getKto() {
		return this.kto;
	}

	public void setKto(String kto) {
		this.kto = kto;
	}

	public String getPc() {
		return this.pc;
	}

	public void setPc(String pc) {
		this.pc = pc;
	}

}
